### ISSUE TITLE
Tree broken on current Firefox DE

### ISSUE THREAD

**Issue by heftig** [piroor/treestyletab#1028]
On the current developer edition (45.0a2; https://github.com/mozilla/gecko-dev/commit/d883518) the current TST (d5b05b6) doesn't work correctly.

Steps to reproduce from a clean profile + TST:

1. Open new tab
2. Open 2+ child tabs from the tiles
3. Close the parent tab (works fine)
4. Close the new parent tab

Remaining child tabs aren't handled correctly: visually they are child tabs, yet they behave like root tabs.

**Comment by heftig** [comment]
I've attempted reverting to older TST versions without success, so I believe this got broken by a recent change in FDE.

**Comment by piroor** [comment]
As the comment https://github.com/piroor/treestyletab/issues/1030#issuecomment-174439208 this issue is possibly fixed by recent commits. Could you try the latest revision?

**Comment by heftig** [comment]
Not fixed yet.

**Comment by heftig** [comment]
Still an issue using FDE 46.0a2 (https://github.com/mozilla/gecko-dev/commit/65c5725d2557fdcf8384f5cc504bca985edc781d).

In a non-e10s window, things seem to work fine.

It seems tabs are not reparented correctly when their parent tab is an e10s-tab and gets closed.

The reason step 3 above works is because about:newtab is not e10s, while the promoted child tab closed in step 4 is e10s.

**Comment by heftig** [comment]
I think I found the cause. I noticed these messages in the browser console when closing such a tab:
```
06:40:40.994 uncaught exception: 2147500033 browser.xml:451:1
06:40:40.994 NS_ERROR_NOT_IMPLEMENTED: Method not implemented'Method not implemented' when calling method: [nsIWebNavigation::sessionHistory] browser.xml:451:0
```

Recent commits to aurora were:
- https://github.com/mozilla/gecko-dev/commit/54c3bd9 Bug 1233803 - Add sessionHistory shim for gBrowser and remote browsers. r=krizsa, a=sylvestre
- https://github.com/mozilla/gecko-dev/commit/47cc12f Bug 1233803 - Add RemoteWebNavigation sessionHistory shim for addons. r=krizsa, a=sylvestre
- https://github.com/mozilla/gecko-dev/commit/d6161b5 Bug 1233803 - Outlaw usage of sessionHistory CPOW in browser code. r=felipe, a=sylvestre

Dummying out the `sessionHistory` access seems to restore normal operation (at least for non-group tabs):
```diff
diff --git i/modules/base.js w/modules/base.js
index 928aa3c..18165aa 100644
--- i/modules/base.js
+++ w/modules/base.js
@@ -2251,6 +2251,7 @@ var TreeStyleTabBase = inherit(TreeStyleTabConstants, {
  
 	isGroupTab : function TSTBase_isGroupTab(aTab, aLazyCheck) 
 	{
+		return false;
 		return (
 			(aLazyCheck || aTab.linkedBrowser.sessionHistory.count == 1) &&
 			aTab.linkedBrowser.currentURI.spec.indexOf('about:treestyletab-group') == 0
```

**Comment by piroor** [comment]
Thanks, confirmed!

**Comment by piroor** [comment]
The commit cf6e1c4f1cf27ea29f2a89ec0ae74a3785a9d829 fixes the problem for me.

**Comment by heftig** [comment]
Fixed indeed, thanks.
