### ISSUE TITLE
Option "next sibling of the current tab" is broken

### ISSUE THREAD

**Issue by rstarkov** [piroor/treestyletab#1193]
## Short description

I have new blank tabs open as "the next sibling of the current tab". Since a few days ago this has been broken across all of my installs: when the current tab is the parent of several other tabs, the new blank tab is inserted at the wrong place and completely messes up the tree.
## Steps to reproduce
1. Start Firefox with clean profile.
2. Install TST.
3. In TST options, select "the next sibling of the current tab" under "New Tabs"
4. Create a tab tree like this:
   - tab 1
     - tab 2
       - tab 3
   - tab 4
5. Activate tab 2
6. Press Ctrl+T
## Expected result

```
 - tab 1
   - tab 2
     - tab 3
   - new tab
 - tab 4
```
## Actual result

```
 - tab 1
   - tab 2
   - new tab
     - tab 3
 - tab 4
```

This doesn't make "new tab" the parent of "tab 3"; "tab 2" remains the parent of that tree.
## Environment
- Platform (OS): Win 7, Win 10
- Version of Firefox: 48.0.2
- Version (or revision) of Tree Style Tab: 0.18.2016090802

**Comment by piroor** [comment]
Confirmed on 0.18.2016090802, and this doesn't happen on the latest development build. It seems fixed by recent commits. Thus I mark this "fixed".

**Comment by rstarkov** [comment]
@piroor This bug is still present in 0.18.2016111701 but only in the last subtree in the list of tabs. STR:

    - tab1
      -tab2
    - tab3
      -tab4

Select tab3, press Ctrl+T. Result:

    - tab1
      -tab2
    - tab3
    - [new tab]
      -tab4

**Comment by piroor** [comment]
I close this because the rest problem is tracked at #1221.
