### ISSUE TITLE
Link opened from pinned tab goes to beginning of tree

### ISSUE THREAD

**Issue by theres-waldo** [piroor/treestyletab#1360]
This is an issue with the WebExtension version of TST.

A link opened from a pinned tab currently goes to the beginning of the tree, in spite of the "Insertion position of new child tabs" option being set to "Append to the last of the tree".

I think that either the position should respect the "Insertion position of new child tabs" option, or there could be a new option for it.

**Comment by piroor** [comment]
Done by d905292. Thanks.

**Comment by theres-waldo** [comment]
Has this fix appeared in a release? I am still seeing it in version 2.0.7, which I assume is the newest ("check for updates" did not detect a newer release).

**Comment by TheSweetLily** [comment]
I am not having this issue.

Using latest nightly build from: http://piro.sakura.ne.jp/xul/xpi/nightly/
