### ISSUE TITLE
Whole trees are closed when tab bar is not open

### ISSUE THREAD

**Issue by Katrix-** [piroor/treestyletab#1418]
## Short description
When closing a tab tree with the tab bar closed, the entire tree is closed. Note, it does not seem to happen when opening a new window 

## Steps to reproduce

 1. Start Firefox with a clean profile.
 2. Install TST.
 3. Open up 3 fresh tabs and arrange them in a tree
 4. Close tab bar
 5. Close first and second tab too. The third tab will be closed too.

## Expected result

The third tab is not closed

## Actual result

The third tab (and any other tab in that tree too) is closed

## Environment

 * Platform (OS):  Windows 10
 * Version of Firefox: 58.0a1 (2017-10-03) (64-bit)
 * Version (or revision) of Tree Style Tab: WE 2017-10-04 20:10

**Comment by piroor** [comment]
By recent commits I've added an option to apply tree behavior for tabs when the sidebar is closed (and the default value of this option is now `true`). This change can affect to your case.

 * Basically if you close a tab and the tab has collapsed descendants, they are also closed. This is an expected behavior of TST.
 * However, on old versions (2.0 - 2.0.2), TST was designed to not apply the behavior when the sidebar is closed. In other words, on such case TST should close only the parent tab and internally promote the first child to the new parent to keep tree structure. On the other hand, in your environment, TST seems to close descendants with the parent tab regardless the sidebar is closed. This is unexpected result for me.

Could you try the latest development build?

**Comment by Katrix-** [comment]
I think I found the option you mentioned and enabled it, but I'm still seeing the same behavior.

**Comment by piroor** [comment]
Could you describe steps to reproduce with figures like #1429 ?

**Comment by nshtg** [comment]
@piroor 
I can't really describe it like this (I'm too tired right now) but I still see the very same bug using the newest nightly build (of both firefox and TST - namely 2.0.2.5369). The option you mentioned above is set.

I just open a new window (google) search for something (barron trump), open three child windows, enter one of them and then middle-click the parent window to close it. As a result it closes all the children the window itself.

I made you a video:

https://my.mixtape.moe/mcjzgo.webm

**Comment by piroor** [comment]
I'm very sorry, the option actually didn't work for some cases. The commit cebeacc should fix this problem.

**Comment by nshtg** [comment]
I can confirm 2.0.3 fixed the bug.

**Comment by nshtg** [comment]
I'm afraid I have to withdraw my statement, the bug still happens sometimes. I do not have found a safe way to reproduce it yet, but from time to time it still happens. Really weird...

**Comment by nshtg** [comment]
@piroor 
I've been trying around. I can not always reproduce it. Starting firefox new fixes the bug for a time, but after surfing a while and using the browser the bug begins and when it's started it is reproducible.

https://my.mixtape.moe/ymhvzq.webm

Take this as an example. I surfed normally before,  suddenly the bug happend. I closed all tabs until only 1 was left, opened a new one on amazon.de searched for sth, opened two children, then middle-clicked the parent tab and it closed both children aswell.

Doing the same thing in a new window does nothing and everything works as it is expected.

Weird...
