### ISSUE TITLE
Duplicate tab of tree can appear in wrong position

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1436]
## Short description
Duplicate tab of tree can appear in wrong position

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Tree structure:
```
A (selected)
\- B
```
 4. Duplicate tab via menu OR middle-click on reload button

## Expected result
Tree structure:
```
A
\-B
A-dup
```

## Actual result
Tree structure:
```
A
A-dup
\-B (although still child of A)
```

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b5
 * Version (or revision) of Tree Style Tab: Latest nightly as of commit f65ea7b1a02ddcb5ead6eac7a2ef5d6f2dfd495c

**Comment by piroor** [comment]
Fixed by 12a7faf, thanks!

**Comment by lbmaian** [comment]
I'm still getting this on the latest nightly. Middle-clicking reload button seems to work, but not the duplicate tab menu item.

**Comment by piroor** [comment]
"tab menu item" means the one in TST's fake context menu? or Firefox's native?

**Comment by lbmaian** [comment]
I mean the one from TST's fake context menu. Firefox's native context menu and middle-clicking the reload button both seem to work fine, but the fake context menu one doesn't.

**Comment by lbmaian** [comment]
Can no longer reproduce with fixes for #1437
