### ISSUE TITLE
Context menu should appear on right mouse-up rather than right mouse-down

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1441]
## Short description

Context menu should appear on right mouse-up rather than right mouse-down. Unlike middle-click, the context menu should be associated with the tab/tab-bar/tec that mouse-up occurred on.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.

### Case I
 3. Hold down right mouse button (mousedown) on a TST tab or tab bar
 4. Move mouse to another tab X
 5. Release right mouse button (mouseup)

### Case II
 3. Hold down right mouse button (mousedown) on a TST tab or tab bar
 4. Move mouse to tab bar
 5. Release right mouse button (mouseup)

### Case III
 3. Hold down right mouse button (mousedown) on a TST tab or tab bar
 4. Move mouse to content window
 5. Release right mouse button (mouseup)

## Expected result

Case I: Context menu appears for tab X upon mouseup.

Case II: Right-click menu appears for tab bar upon mouseup.

Case III: Nothing, let Firefox show its default context menu.

## Actual result

Context menu appears immediately upon mousedown.

In case III, note that the TST context menu appears initially, then the Firefox default context menu appears once mouseup occurs in the content window.

## Environment

* Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
* Version of Firefox: Developer Edition 57.0b5
* Version (or revision) of Tree Style Tab: 2.02

**Comment by piroor** [comment]
Done by e116b61. Thanks!

**Comment by lbmaian** [comment]
The last test case still isn't working properly.

If you hold right click down then move it into the content window, both the TST context menu and Firefox's context menu appear on mouseup.

**Comment by piroor** [comment]
Changes for #1439 should fix this also.

**Comment by lbmaian** [comment]
Case III still doesn't look fixed on the latest nightly. Both TST context menu in the sidebar and Firefox context menu in the content window appear upon mouseup.

**Comment by piroor** [comment]
Sorry I misunderstood. 1c0cf61 should fix this.

**Comment by lbmaian** [comment]
Regression from the latest fix: now cases I and II don't work anymore.

There's also another edge case, but I'm not sure if it's fixable in TST - case IV:
3. Hold down right mouse button (mousedown) on content window
4. Move mouse to TST sidebar
5. Release right mouse button (mouseup)

Expected result: TST context menu appears for mouseup'ed tab or tab bar.

**Comment by piroor** [comment]
BTW I've realized that the context menu should appear on mousedown on Ubuntu - the timing to show the context menu seems different on each platform. I think this behavior should be applied on Windows (and macOS?)

**Comment by lbmaian** [comment]
Huh, that's definitely not how things work in Windows. In pretty much all applications, including Firefox itself, the context menu appears on right-click mouseup.

I don't recall on macOS - haven't used in an Apple for a long time - but I think it may also trigger on mousedown rather than mouseup (according to some googling).

The differing behavior between operation systems means there should be an abstract context menu event, rather than OS-specific right mousedown/mouseup events. There's also the context menu key on standard keyboards to support. Perhaps the following is applicable? https://developer.mozilla.org/en-US/docs/Web/Events/contextmenu

**Comment by piroor** [comment]
Until I read your comment https://github.com/piroor/treestyletab/issues/1441#issuecomment-335206172 I forgot that I canceled `contextmenu` event to block Firefox's default menu. After 57d7c13 the trigger of the menu is changed to Firefox's `contextmenu` event so it should fix this problem on all platform.

**Comment by lbmaian** [comment]
Thanks, confirmed fixed for me.
