### ISSUE TITLE
New child tabs are not shown (for certain TST settings)

### ISSUE THREAD

**Issue by Awerick** [piroor/treestyletab#1551]
## Short description
New child tabs are not shown in TST's tab bar (for certain TST settings).
(Alternative description: If a tab becomes a parent, it is not expanded (for certain TST settings).)

![treestyletabs - bug marked](https://user-images.githubusercontent.com/23130393/32920190-af9f0a92-cb28-11e7-92d9-f0c45a78f9ea.jpg)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. In TST settings: Disable the following two options:
    [ ] When a tab gets focus, expand its tree and collapse others automatically
    [ ] Expand tree automatically, when tabs are inserted into the tree
 4. From a tab with no children yet: Open a link as a children.
    (The bug appears in _most_ cases but not always.)

## Expected result
New Tab should be shown in TST's tab bar.

## Actual result
Tab is not shown (however the parent tab shows the arrow that indicates, that there is a child tab).
(If one clicks the arrow on the parent tab twice, i.e. uncollapse and collapse the child tabs, the child become visible.)

## Environment
 * Platform (OS): Linux
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.8 (but problem exists since ~1 week)

**Comment by piroor** [comment]
Thanks. 6864938 should fix this.

**Comment by Awerick** [comment]
Thanks for the quick fix!

One edge case seems to remain: If one opens a new child via middle click on the "New Tab" button, the problems still arises.

**Comment by piroor** [comment]
Recent commits should fix the remaining problem. However, to simplify the implementation, I've removed the configuration "Expand tree automatically, when tabs are inserted into the tree". Now a tree is always expanded automatically when a tab is attached to another manually (drag and drop, open new tab, etc.) In other words, only session restoration is the case to keep tree collapsed after a child is attached.

**Comment by Awerick** [comment]
Thanks again!
