### ISSUE TITLE
Vertigo theme: white background on the left of children tabs

### ISSUE THREAD

**Issue by 3c0** [piroor/treestyletab#1572]
## Short description

The vertigo theme has a small cosmetic issue.

## Steps to reproduce

 1. Install TST.
 2. Select the Vertigo theme in TST options.
 3. Open a window with at least one child tab.

## Expected result

There should be no white background on the left of children tabs.

Note that the screenshot of the Vertigo theme in TST options does **not** exhibit this cosmetic glitch:
![Vertigo theme screenshot](https://raw.githubusercontent.com/piroor/treestyletab/2db4f7b0c65242239dcd8b9eb88d2d42c7a6a9ff/webextensions/options/style-vertigo.png) 

## Actual result

![Vertigo theme white space on the left of children tabs](https://user-images.githubusercontent.com/7715141/32980652-d03197dc-cc6a-11e7-9945-10484a7db6e0.png)

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by piroor** [comment]
Thanks! e1a71fc should fix this.

**Comment by 3c0** [comment]
Fix confirmed 😎, closing issue.

**Comment by damat** [comment]
Hmm, I'm on the latest version of the Firefox and Tree Style Tab, but the issue is still presented. Checked the sources, there's no update from the commit mentioned above.
What should  I do?

**Comment by 3c0** [comment]
@damat We have to wait for @piroor to publish the next TST release that will contain this fix among others... 🏭 ⌚️ 👀 

I have personally tested the fix e1a71fc by directly patching the xpi file, but it is a cumbersome process. 😫

**Comment by damat** [comment]
@3c0 , I've patched mine as well but ended up with corrupted extension =) Reinstalled it, and posted the question here =)
Thank you for the update! I'll wait patiently

**Comment by TheSweetLily** [comment]
You can download latest TST on Piro's website: http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by damat** [comment]
@thesweetlily, I've tried but Firefox prevented the install: https://dl.dropboxusercontent.com/s/ujgc6f7sulmvj1j/shot_171123_171536.png

**Comment by TheSweetLily** [comment]
Ah, right. 
If you use xpinstall.signatures.required you can allow the install, although I think it's disabled on the stable release version(?).

**Comment by 3c0** [comment]
@damat As you patch the xpi file, its signature becomes invalid and so Firefox barks at you. If you use Firefox Nightly or Developer edition, you can set `xpinstall.signatures.required` to `false` in `about:config`, but I would advise against doing so for security reasons. ☠️ 

@TheSweetLily Either way, we would loose AMO extensions auto update feature, wouldn't we ?

**Comment by damat** [comment]
it doesn't work even when this setting is disabled

**Comment by damat** [comment]
@3c0, yep, I do understand the risks, so waiting patiently
Btw, the update is just awesome =)

**Comment by 3c0** [comment]
@TheSweetLily Even if you install a TST nightly build ?

**Comment by TheSweetLily** [comment]
Yeh, that's been the case for me.

**Comment by 3c0** [comment]
@TheSweetLily It appears that you're right ! 😲 @piroor is mixing TST _nightly_ and _release_ channels... 🙁

Issue reported in #1610.

**Comment by 3c0** [comment]
Bug is back in version 2.4.6 !

**Comment by 3c0** [comment]
Looks like it is somehow related to #1733. Adding this CSS snippet seems to fix it : 
```css
:root, #background {
  background: var(--tab-surface);
}
```

**Comment by damat** [comment]
Thank you, @3c0 ! 
I wasn't able to figure it out by myself =( But now it's fixed forever =)

**Comment by piroor** [comment]
Thanks! 5465877 should fix this.
