### ISSUE TITLE
[Regression after TST 2.3.0] "open new blank tab" setting ignored when Ctrl-T

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1657]
## Short description
There's been a regression after TST 2.3.0 (but not in TST 2.3.0 itself) in the nightly builds, where the "open new blank tab" setting is apparently ignored, and all new blank tabs are opened as independent tabs.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set TST "Open new blank tab as" option to anything other than "an independent tab" (e.g. "a sibling of the current tab")
 4. Tree structure:
```
A
\- B (selected)
```
 5. Open a new tab via Ctrl-T

## Expected result
If option set to "a sibling of the current tab":
```
A
|- B
\- new_tab (selected)
```

## Actual result
```
A
\- B
new_tab (selected)
```

## Environment

 * Platform (OS): Windows 10 Pro (64-bit), Version 1709, Build 16299.98
 * Version of Firefox: Developer Edition 58.0b8 x64 or Nightly 59.0a1 (2017-12-04) x64
 * Version (or revision) of Tree Style Tab: 2.3.0.6045

**Comment by lbmaian** [comment]
Possibly related: attempting to open a child tab by middle-clicking a link results in a next sibling of the ancestor root tab, rather a child tab:

STR:
1. Tree structure:
```
A
\- B (selected)
C
```
2. Open child tab by middle-clicking a link

Expected result:
```
A
\- B (selected)
    \- child_tab
C
```

Actual result:
```
A
\- B (selected)
child_tab
C
```

**Comment by lbmaian** [comment]
Another possibly related issue: when "open new blank tab as" option is set to either "a sibling of the current tab" or "the next sibling of the current tab", a new tab opened by the TST new tab button does appear as a sibling, but as _previous_ sibling:

STR:
1. Set TST "open new blank tab as" option is set to either "a sibling of the current tab" or "the next sibling of the current tab".
2. Tree structure:
```
A
\- B (selected)
```
3. Open new tab via clicking TST new tab button

Expected result:
```
A
|- B
\- new_tab (selected)
```

Actual result:
```
A
|- new_tab (selected)
\- B
```

If you close a tab previously and undo close tab (ctrl-shift-T), it also messes up the tree structure and can even result in a hidden tab.

**Comment by piroor** [comment]
Thanks. 94e44b2 should fix this.

**Comment by lbmaian** [comment]
Thanks, this looks fixed. The undo close tab problem still happens though - will document another STR in #1633
