### ISSUE TITLE
Group tab not loaded correctly on session restore at Firefox startup

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1731]
## Short description
When I restore my session at Firefox startup I usually have a group tab as the selected tab on each of my windows. When Firefox has started I usually, but not always, have to reload all of these selected group tabs to get them to show the correct content. They have two incorrect states that they can end up in. Either they are totally white with no content (I assume they were loaded before TST were loaded) or all of the elements on the page have their placeholder names (so the JavaScript wasn't injected correctly).

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Configure Firefox to restore last session on startup.
 4. Make Firefox slow to start. Maybe open a lot of tabs and install some heavy extensions.
 5. Open a group tab and select it.
 6. Restart Firefox.

## Expected result
Firefox should start with the selected group tab loaded correctly.

## Actual result
Firefox start with the selected group tab loaded incorrectly. It has no elements or has placeholder names for the elements.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.4.3

**Comment by piroor** [comment]
I think the commit 7271868 should fix this.

**Comment by Lej77** [comment]
@piroor I tested the latest TST build (v2.4.3.6327) and this issue doesn't seem fixed. I can still quite easily get group tabs with placeholder named elements when I restart Firefox and have a group tab as selected tab.

Example of placeholder named elements:
![script injection failed](https://user-images.githubusercontent.com/31554212/35383080-835290ec-01c1-11e8-92fe-9b63d5d81337.png)

**Comment by Lej77** [comment]
I tested TST v2.4.3.6329 and still get placeholder named elements. Also your commits seams to be about the tab's title which isn't the issue, it seems to be correct. The issue is about the webpage elements that are used to customize the group tab, the script to control them doesn't seem to be injected correctly.

**Comment by Lej77** [comment]
Also here is an example of the group tab without any elements: 
![tab without elements](https://user-images.githubusercontent.com/31554212/35384126-9dca1096-01c4-11e8-865a-6a58cc2d858f.png)
The tab has the correct title but the page to change the title isn't loaded correctly. Selecting another tab and then re-selecting the bugged tab doesn't fix the problem (unlike the group tab with placeholder named elements). Reloading the tab does fix the problem.

**Comment by Lej77** [comment]
The tab without any elements have an empty body.

**Comment by Lej77** [comment]
@piroor I saw that you made the commit [f3cf01c](https://github.com/piroor/treestyletab/commit/f3cf01c0e9273f0ac1fe1bdc22c10e63bc3c7abd). It seems to load even unloaded tabs on startup. I think it would be better to avoid initiating any unloaded tabs if possible. That is to say if a tab is discarded it should remain discarded until the user requests otherwise. Instead I think only loaded tabs should be reloaded.

**Comment by Lej77** [comment]
This seems fixed on TST 2.4.9.
