### ISSUE TITLE
"Move current tab/tree down" not working.

### ISSUE THREAD

**Issue by gwenzek** [piroor/treestyletab#1840]
## Short description

Since FF60 you added the ability to set up shortcuts to move tab around which is very nice.
"Move Current Tab Up" and "Move Current Tree Up" do work as expected.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Go to TST preferences
 4. Set "ctrl+." as a shortcut for "Move Current Tab Down"
 4. Set "ctrl+," as a shortcut for "Move Current Tab Up"
 5. Press "ctrl+.", the current tab moves up as expected.
 6. Press "ctrl+,", nothing happen while the tab should move down.

The same can be done with "Move Current Tree" instead.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 60.0b4
 * Version (or revision) of Tree Style Tab: 2.4.17

**Comment by kulmegil** [comment]
## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: nightly 61.0a1 2018-04-15, 64-bit
 * Version (or revision) of Tree Style Tab: build 2018-04-13

**Comment by piroor** [comment]
Thanks, this has been fixed by the commit 6afe106.

**Comment by gwenzek** [comment]
Thanks, I still see the issue, but I guess it's because the fix haven't been released yet.
