### ISSUE TITLE
Default favicon for tab in sidebar dependent on previously opened page

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1916]
## Short description
The default favicon in the sidebar is sometimes changed to a special favicon used on the same tab previously. In my normal session this happens when I unload a tab (due to a Firefox bug it then loses its favicon) and then close and reopen the sidebar. The favicon on tabs that are missing the `favIconUrl` property should be set to the default favicon but on tabs that were navigated from a special tab such as the new tab page (`about:newtab`) or the private browsing page (about:privatebrowsing) the favicon is set to the special page's favicon. It is confusing to have the new tab favicon for tabs that are actually normal web pages. 

I wrote the following CSS which fixes most of my issues:
```css
/* TST 2.4.22 - Fix for sepcial favicons as default favicon after navigating from special url */
.tab:not(.loading):not([data-current-uri^="about:"]):not([data-current-uri^="chrome:"]):not([data-current-uri^="moz-extension:"]) .favicon .favicon-image:-moz-any([src^="chrome:"], [src^="moz-extension:"]) {
  display: none !important;
}
.tab:not(.loading):not([data-current-uri^="about:"]):not([data-current-uri^="chrome:"]):not([data-current-uri^="moz-extension:"]) .favicon .favicon-image:-moz-any([src^="chrome:"], [src^="moz-extension:"]) ~ .favicon-builtin::before  {
  display: inline-block !important;
}
.tab.group-tab .favicon-image {
  display: none !important;
}
```

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a new private window.
 4. Open a new tab in the private window with the URL `about:privatebrowsing`.
 5. Navigate the new tab to the URL `about:blank`.
 6. Close and reopen Tree Style Tab's Sidebar.

## Expected result
The tab should have the same favicon before and after closing and reopening the sidebar.

## Actual result
The tab's favicon changes from the default favicon to the `about:privatebrowsing` favicon.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 60.0.1
 * Version (or revision) of Tree Style Tab: 2.4.22

**Comment by piroor** [comment]
Thanks. The commit 314e98c should fix this case.

**Comment by sebastianiorga** [comment]
This bug still seems to be happening in Ubuntu, Firefox 64.0b3, TST 2.6.4.

**Comment by piroor** [comment]
I've realized that on such cases actually updated "favIconUrl" is not notified via browser.tabs.onUpdated. After the commit 54277cb favicon of tabs are always synchronized to the native tab.
