### ISSUE TITLE
tab-mouseout event fired while still on tab

### ISSUE THREAD

**Issue by klemens** [piroor/treestyletab#1992]
## Short description

27747f6fc433f8f452fed85f7cf0d29c5af5caf4 implemented support for `mouseover` and `mouseout` events. However, `mouseout` is currently not very useful, as it also fires when moving from a tab (`li`) to one of its children (`span`, e.g. the title or favicon). This makes it impossible to know when the cursor actually leaves the tab.

## Steps to reproduce

1. <details>
    <summary>Install the following example add-on:</summary>

    ```js
    const TST_ID = "treestyletab@piro.sakura.ne.jp";

    async function registerToTST() {
        try {
            var success = await browser.runtime.sendMessage(TST_ID, {
                type: "register-self",
                listeningTypes: ["tab-mouseover", "tab-mouseout"]
            });
        } catch(e) {}
    }

    browser.runtime.onMessageExternal.addListener(async (message, sender) => {
        if(sender.id !== TST_ID) { return; }
        let tab = message.tab;
        switch (message.type) {
            case "ready":
                registerToTST();
                break;
            case "tab-mouseover":
                console.log("enter tab " + tab.id);
                break;
            case "tab-mouseout":
                console.log("leave tab " + tab.id);
                break;
        }
    });
    registerToTST();
    ```
    *Note:* For me `mouseover` and `mouseout` only work after reopening the sidebar (`mousemove` works directly after installing the add-on). However, I haven't checked the dev-version or a clean profile, I just wanted to mention it in case you want to test the example.
    </details>
2. Move mouse over tab
3. Move mouse away from tab

## Expected result

```
enter tab 1
* mouse now on tab (title) *
leave tab 1
* mouse no longer on tab *
```

## Actual result

```
enter tab 1
leave tab 1
* mouse now on tab (title) *
* mouse no longer on tab (no event!) *
```

## Fixes

One solution is to ignore the `mouseout` event when the cursor leaves the tab for one of its children using the `relatedTarget` attribute of the event, which contains the target of the corresponding `mouseover` event using something like `!target.classList.contains("tab") || target.contains(e.relatedTarget)`. I think this also makes the current logic that prevents multiple consecutive events from the same tab obsolete.

Another solution is to use `mouseenter` and `mouseleave` events, which are [not firing](https://developer.mozilla.org/en-US/docs/Web/Events/mouseenter) when entering or leaving children of an element. However, these would have to be added to every tab individually, as they don't bubble.

I can create a pull request with any of these changes if you want.

<details>
<summary>Simple test of the first solution</summary>

```html
<nav id="tabs">
    <div class="tab" data-id="1" style="padding: 30px; background: orange;">
        <p style="height: 100px; background: gray;"></p>
    </div>
    <div class="tab" data-id="2" style="margin: 10px 0; padding: 30px; background: orange;">
        <p style="height: 100px; background: gray;"></p>
    </div>
    <div class="tab" data-id="3" style="padding: 30px; background: orange;">
        <p style="height: 100px; background: gray;"></p>
    </div>
</nav>
<script>
    let tabs = document.getElementById("tabs");

    tabs.addEventListener("mouseover", (e) => {
        // Ignore if not a tab or entering from a child (relatedTarget)
        if(!e.target.classList.contains("tab") || e.target.contains(e.relatedTarget)) {
            return;
        }
        console.log("enter: " + e.target.dataset.id);
    });
    tabs.addEventListener("mouseout", (e) => {
        // Ignore if not a tab or leaving to a child (relatedTarget)
        if(!e.target.classList.contains("tab") || e.target.contains(e.relatedTarget)) {
            return;
        }
        console.log("leave: " + e.target.dataset.id);
    });
</script>
```
</details>

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 62b12
 * Version of Tree Style Tab: 2.4.24

##

**Comment by piroor** [comment]
Thanks. The commit 5e9d201 should fix this.

**Comment by klemens** [comment]
Thanks for the fix. However, this still does not work very well. For example the `mouseout` event is not sent when leaving the tab and sidebar at the same time (eg when moving the mouse out the top onto the url bar), but only when moving the mouse back over the sidebar.

I am trying to reimplement the TMP functionality of using mouse hovering to change tabs after a certain delay and the `mouseout` event is needed to stop the timer when leaving the tab. Otherwise, the top tab is always activated when moving the mouse over the tabs to the url bar for example.

I implemented a refined version of the fix I proposed above in #2008 and it works mostly fine. The only remaining problem is that firefox sometimes emits a `mouseover`, but no corresponding `mouseout` event. It seems very similar to [bugzilla 577785](https://bugzilla.mozilla.org/show_bug.cgi?id=577785), which is unfixed since 2010, so there is probably not much we can do here.
