### ISSUE TITLE
Sticky tab tooltips

### ISSUE THREAD

**Issue by RyanSattler** [piroor/treestyletab#2022]
## Short description

When I sweep my mouse over the vertical tab list on the left, tab tooltips (that normally pop up on hover) sometimes get "stuck" and won't go away until you mouse over them again.

This doesn't happen for the built-in horizontal tabs at the top.

## Expected result

The tooltips disappear when the mouse is not over the tab in question.

## Actual result
They sometimes stick around - both the tab-title tooltips, and the "close tab" tooltip from the x button.

## Environment

 * Platform (OS):  MacOs
 * Version of Firefox: 61.0.2 
 * Version (or revision) of Tree Style Tab: 2.5.3

**Comment by piroor** [comment]
This doesn't happen for me on macOS. I think it is a problem of Firefox itself, because TST doesn't control how to show tooltips - they are just defined as "title" attribute like regular webpages.

**Comment by RyanSattler** [comment]
It seems like I can stop this from happening by closing and reopening the TST sidebar.

**Comment by mruhlin** [comment]
FYI when this happens it's the result of Firefox not knowing when you've moved the mouse outside the window.  So it keeps the "hover" state active wherever the cursor used to be.  It thinks it's supposed to show the tooltip because it thinks the mouse is still there.

I think I successfully worked around it by adding the following custom CSS:

```
.tab {
 margin-left: 1px;
 margin-right: 1px;
}
```

Basically this just adds 1 pixel on the left and right sides of the tab, so firefox thinks your mouse is hovering there, not on the tab itself.

**Comment by rdewolff** [comment]
Same issue here on macOS with Firefox. Tooltip sticks, pretty annoying.

**Comment by davojan** [comment]
Can we just have an option in preferences to disable tooltips completely? Just don't add that title attribute and there will be no annoying tooltips at all.

**Comment by rdewolff** [comment]
That'd be a great addition!

**Comment by piroor** [comment]
I'm nevative to add new option just for a workaround, and I believe that it should be tracked as a bug of Firefox itself.

By the way I still cannot reproduce the problem on my environment macOS Sierra (10.12.6). Could anyone post a screencast how to reproduce the problem?

**Comment by mruhlin** [comment]
Here's a video of the bug in action: https://gfycat.com/SoggyIdleHornedtoad  My CSS trick didn't do any good.  The worst part for me is that the tooltip stays on top when I go to another window.

Not sure exactly what gets me into this state, but once I am it happens every time I mouse-out of the sidebar.

A thing I noticed today that might be a coincidence:  I usually work on a MacBook Pro connected to an external monitor.  If I close and restart Firefox, the problem goes away.  If I then unplug my macbook from the monitor, this starts happening again (and continues to happen after I re-connect the monitor).  I think maybe something breaks in Firefox when the windows get rearranged between monitors?  

So, I understand calling it Firefox's fault, but a workaround would be nice, especially given the annoyance that the titles stay popped up while other windows are active.

**Comment by piroor** [comment]
@mruhlin Thanks a lot! Hmm, however I still cannot reproduce the problem on my environment. On your video, the tooltip appears after you move the cursor out from the sidebar. On the other hand, on my environment the tooltip doesn't appear oni such a time. I tried again and again, but a tooltip never never appear when the cursor is out of the sidebar, instead the tooltip appears when the cursor is on the sidebar and disappears immediately when I move the cursor.

On you video, the color of the tab that the tooltip appears on looks changed after you moved the cursor out. It is not an expected behavior, and the color of hovered tab should be updated more quickly. It looks that the Firefox on your environment looks too slow due to something reason. If your Firefox is really slow, the core trigger of the problem sticky tooltip may be the "slow Firefox" itself. Is there any possible reason triggering the slowing?

**Comment by mruhlin** [comment]
Yeah I see what you mean, not sure what that's about.  At the beginning of the video the hover color is tracking the mouse much more quickly.

I do get the occasional issue where Firefox will eat up a ton of CPU and start to lag like that (haven't figured out the cause.  Maybe an extension or maybe just Firefox itself), but I don't think it's related since I see this happen a lot of times when there insn't any apparent slowness going on.

**Comment by acarp52** [comment]
I have experienced this bug as well, as described but with newer versions of Firefox and TST. I have a similar workflow; generally I work off an external monitor with my MacBook lid closed, but frequently disconnect and reconnect my machine throughout the day.

I don't have a solution or a root cause, but I have found a quick and easy workaround:
Simply toggling TST on and off (by default mapped to F1) prevents the bug from showing, at least for a while.

**Comment by letterq** [comment]
I have also experienced this issue. 
Firefox 67.0.2 
Tree-style tab 3.1.1

**Comment by antanst** [comment]
This still persists on Firefox 68 on MacOS. Closing and reopening the sidebar fixes it temporarily.

**Comment by piroor** [comment]
1561570 - Tooltips for elements in WebExtensions sidebar are misplaced after entering a fullscreen video
https://bugzilla.mozilla.org/show_bug.cgi?id=1561570
I think this problem should be tracked on bugzilla as a bug of Firefox itself like above.

**Comment by irvinm** [comment]
Looks like this will be fixed in FF69.  The defect is currently marked as verified fixed.

**Comment by irvinm** [comment]
@piroor I believe this issue has been fixed and released and this issue can be closed.

**Comment by piroor** [comment]
Thank you for a reminder, I forgot to close this.

**Comment by jastice** [comment]
I still have this problem all the time. Most commonly the "close tab" tooltip gets stuck, and stays that way even when switching windows

Currently on TST 3.3.6 (2020.2.21), FF 73.0.1 (64-bit), macOS 10.14.6

**Comment by expelledboy** [comment]
Still an issue for me, trying what was suggested here: http://forums.mozillazine.org/viewtopic.php?f=7&t=342902

```
.tabbrowser-strip tooltip {
   display:none ;
}
```

**Comment by piroor** [comment]
@expelledboy It hides the tooptip on Firefox's native tabs. The CSS rule doesn't affect to TST because the tooltip on TST's sidebar is implemented by Firefox as a tooltip for webpages. Instead you need to use a CSS rule like following:

```css
// put this into userChrome.css
#remoteBrowserTooltip {
  display: none !important;
}
```

But as a side effect it also hides all tooltips on regular webpages...

**Comment by aiba** [comment]
Is there no way to construct a CSS selector that targets only TST tooltips?

**Comment by piroor** [comment]
@aiba No way as far as I know. The on;y one way to solve this problem fundamentally is: modify TST to prevent setting `title` attribute for its sidebar contents, but I don't want to implement such an option sorry. I still think such a sticky tooltip problem should be fixed on Firefox side - it happens with other addons also, not only TST's issue.

**Comment by aiba** [comment]
I see.  Perhaps someone on this thread who is good at reproducing the problem (@mruhlin ?) would be willing to file a new bug on the firefox bugzilla? 

The previous one mentioned on this thread appears to have been closed: https://bugzilla.mozilla.org/show_bug.cgi?id=1561570

I would do it but I still don't have a consistent way to reproduce the problem.  For me (macOS 10.15.4, FF 76.0b2) it only happens a few times per week, but when it does happen it's really annoying.

**Comment by expelledboy** [comment]
The thing is I dont see how this is a firefox bug when this does not happen unless you have TST installed. Could you not just decorate that element with a unique css ID?

**Comment by jarredou** [comment]
Happening sometimes here also...
