### ISSUE TITLE
Close multiple tabs warning shows on all windows instead of one

### ISSUE THREAD

**Issue by MurzNN** [piroor/treestyletab#2122]
I use multiple windows of Firefox, each of them have separate Tabs sidebar. But when I try to close multiple tabs, popup warning `You are about to close [count] tabs. Are you sure you want to continue?` shows on sidebar in all windows, not only on one window, when I try to close tabs. 

It works correctly - even if I press "Ok" on wrong window, it closes tabs in right window. But after pressing "Ok" on some window - the popup is stay visible on all other windows, so I must press "Ok" on all other windows for continue working with tabs. 

For fix this problem - can we detect right sidebar and display popup only in one sidebar?

**Comment by piroor** [comment]
There are multiple methods to close multiple tabs at a time, and they are tracked in different methods. What is the steps you actually closed those tabs? For example: "Close Other Tabs" in the context menu on the sidebar, keyboard shortcut, or others.

**Comment by piroor** [comment]
And, recently I've fixed some bugs around confirmation of tab closing. Could you try with the development build?: https://github.com/piroor/treestyletab/blob/master/README.md#development-builds

**Comment by MurzNN** [comment]
I use `Close tabs to the bottom` item on tab context menu, I retest with current git and bug is still here. How to reproduce: 
1. Open several tabs in one window
2. Open new window and several tabs in it too.
3. Right click on any middle tab in any window and press "Close tabs to the Bottom" or "Close Other Tabs" menu item for close more than 1 tab. TST popup confirmation window will shown on both windows.

**Comment by piroor** [comment]
Thanks! I've successfully reproduced the problem and the problem is fixed by 85d3948.

**Comment by rubaboo** [comment]
Now the warning pops up on a wrong window. I have two windows. I use a keyboard shortcut to close a tree in one of the windows. I see no warning, nothing happening. Then I switch to the other window, and the warning is there.

**Comment by piroor** [comment]
Thanks. The commit 6ab45ee should fix the case about keyboard shortcut.

**Comment by MurzNN** [comment]
Thanks, now all works well!
