### ISSUE TITLE
Can no longer create "Child Tab" 

### ISSUE THREAD

**Issue by noxcovenant** [piroor/treestyletab#2172]
## Short description

The UI doesn't do anything when I select to create a "child tab".  (I've tried the drop-down menu and simply pressing the "+" icon)

Is there a setting I accidentally turned off?  Thanks for any help.
## Steps to reproduce

1. It started happening 3/5/2019.
2. If I create a new Firefox profile, the "new child tab" works.  However, it eventually stops working.

## Expected result

New Child Tab is created.

## Actual result

Simply nothing happens.  Essentially, the UI ignores the command.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox:  Firefox Quantum 61.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.8.0 / 2.8.1

**Comment by piroor** [comment]
Thanks, the commit 0f598b3 should fix this.

**Comment by noxcovenant** [comment]
Thanks for the insanely fast response time.  :)

Unfortunately I still cannot create new child tabs.  I've made sure to upgrade to 2.8.1 too.  I'll keep tinkering around to figure out what changed today.  Because it worked perfectly yesterday.

**Comment by piroor** [comment]
Sorry, I misunderstood that this issue is about Ctrl-T and other cases. It seems to be fixed by c4ea707dfc6186dd2f4c899522ec5bec8cedb8df.

**Comment by remram44** [comment]
I'm having the same issue as of a few hours ago.

Ctrl-T opens a new tab NOT as a child, and the "+" icon doesn't do anything. All items in the drop-down menu work except "child tab" which doesn't do anything.

Not sure if you have already fixed this, will report when it updates.

**Comment by drislands** [comment]
Confirmed that today's nightly build has resolved this error for me. The error I was seeing in the current build is "TypeError: parent is undefined".

**Comment by remram44** [comment]
Auto-updated and fixed for me! (2.8.2)

Thank you for dealing with this so swiftly and for the amazing response time on GitHub! Your add-on is awesome and probably the number one reason I use Firefox at all.

Cheers

**Comment by remram44** [comment]
I'm having a lot of issues with the new versions, though this particular one has been fixed. Opening new tabs have them completely on the left though they are child. Sometimes it gets into a state where clicking on any tab selects the one above it. Sometimes reopening Firefox, my whole tree is flattened. Cycling with Ctrl+Tab goes in wrong order.

![screenshot](https://user-images.githubusercontent.com/426784/54141061-57c6a800-43fb-11e9-81d3-aacdd356b8be.png)

I'm going to try to downgrade, but I thought you should know.

**Comment by piroor** [comment]
@remram44 Something looks wrong on your environment, but the trigger is still unknown. If you successfully reproduce such a broken state from scratch (on a new clean window), detailed descriptions to reproduce that on my PC will help debugging.

**Comment by irvinm** [comment]
@remram44, any update on the situation?  Can we close this item?

**Comment by remram44** [comment]
Creating child tabs works fine :+1:

I still run into a broken state like above from time to time, for example moving multiple tabs from a temp parent to another parent (temp parent disappears during the move, children show up wrong). But otherwise it's been very smooth :heart_eyes:

**Comment by irvinm** [comment]
@noxcovenant can you close this item now?
