### ISSUE TITLE
Tree Style Tab is Disabled 

### ISSUE THREAD

**Issue by j-cimb-barker** [piroor/treestyletab#2258]
## Short description

Tree Style Tab gets disabled on install. Additionally downloading Tree Style Tab from https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/ gets "Download failed. Please check your connection."

I have checked my network connection. All is good. 

I have previously installed Tree Style Tab. It is now marked as a legacy Extension and disabled.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Observe "Download failed. Please check your connection" notice.
 4. Try to open tabs

## Expected result

Tabs vertical like a Tree.

## Actual result

Tabs horizontal at top of screen.

## Environment

 * Platform (OS): OS X 10.14.4
 * Version of Firefox: 66.0.3 
 * Version (or revision) of Tree Style Tab:  3.0.11

**Comment by siikamiika** [comment]
This is a Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by irvinm** [comment]
It should be fixed now.  Please try again and close this item if resolved.

**Comment by j-cimb-barker** [comment]
This is resolved now.

**Comment by Gaia39** [comment]
TST back now - thanks

**Comment by hhegedus** [comment]
I am still having the exact same problem.  Why has this ticket been closed?

**Comment by frougon** [comment]
Same here...

**Comment by justdave** [comment]
The ticket is closed because the problem is with Firefox, not with TST. There is nothing the TST developer can do to fix it, you have to get the update to Firefox to pick up the fix.

**Comment by Gaia39** [comment]
Mine has sorted itself out. I pressed the TST icon in the URL/search bar (at the right) and it then reappeared. I did do the change in the privacy section under privacy & security in Firefox options – tick the box  ‘Allow Firefox to install and run studies.’

Don’t know whether that fixed it or if FF have fixed the error in the interim.

Lynda

**Comment by frougon** [comment]
Thanks for the answers. Indeed, after updating Firefox to version 66.0.4-1 (Debian sid), I was again able to install TST and... the layout of my tabs was restored! :-)
