### ISSUE TITLE
Visually misaligned tree child after Firefox restarts

### ISSUE THREAD

**Issue by azizLIGHT** [piroor/treestyletab#2266]
## Short description
On some Firefox restarts, the tree structure is not rendered properly. Some children are displayed as being at the same level as their parent, however, they still retain their functionality as a child.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Set Firefox preference: check Restore previous session
 3. Install TST.
 4. Load Tree Structure as follows:
![image](https://user-images.githubusercontent.com/8013867/57312019-6d9fd300-70f5-11e9-8dfb-a9e6c0e5df04.png)
5. Close Firefox and open Firefox repeatedly until you see this:
![image](https://user-images.githubusercontent.com/8013867/57311933-42b57f00-70f5-11e9-90bf-634210b9eb14.png)

## Expected result
![image](https://user-images.githubusercontent.com/8013867/57312019-6d9fd300-70f5-11e9-8dfb-a9e6c0e5df04.png)

## Actual result
![treestyletab-misaligned-tree1](https://user-images.githubusercontent.com/8013867/57312440-3a117880-70f6-11e9-98c9-c105c8194241.gif)
![treestyletab-misaligned-tree](https://user-images.githubusercontent.com/8013867/57313891-2c112700-70f9-11e9-940c-19b634874021.gif)
![treestyletab-misaligned-tree2](https://user-images.githubusercontent.com/8013867/57313290-fae42700-70f7-11e9-89cb-471194b65fb1.gif)

It only happens sometimes, and I cannot figure out what causes it besides the speed at which I close and open Firefox again and again. I have tried using other tabs in focus, including the tab L3. I have also tried mousing over the tree structure on load to see if it influences it, but I cannot find the exact cause still. I have yet to confirm if this only happens at this particular level (L4) or others as well. For now, I can reproduce this situation, as it is, only sometimes. I am available to help test and provide logs to help isolate the problem

## Environment

 * Platform (OS): Windows 7 x64
 * Version of Firefox: 66.0.4 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.0.11

**Comment by azizLIGHT** [comment]
I noticed that in Actual Result gif 1, the collapsing and expanding fixed the visual issue there, but not in Acutall Result gif 2. I must add that the TST settings between those two Firefox profiles are slightly different, but otherwise both are fresh Firefox profiles with no other addons

**Comment by piroor** [comment]
Thanks. I've confirmed that this problem happens sometimes, so it looks a timing issue. With the commit f9dbe67 now TST tries to initialize and update the indent level more safely, so I think this problem should be solved.

I need more further testings to confirm the problem is really fixed or not. If you OK, there is an automated build including the fix: https://github.com/piroor/treestyletab/blob/master/README.md#development-builds (but please note that you need to use Nightly or Developer Edition to install such an unsigned messages.

**Comment by stapuft** [comment]
this is very similar to my repeated issues with the tabs order and tree structure upon restoring Firefox sessions.

**Comment by azizLIGHT** [comment]
Still seeing the issue on Firefox Nightly 68.0a1 (2019-05-09) (64-bit) and TST dev build 3.0.11.9104 with a completely fresh and separate Firefox profile
![nightly-TSTdev-misaligned-tree1](https://user-images.githubusercontent.com/8013867/57456481-49b7cb00-7276-11e9-885e-20c986bc4860.gif)

**Comment by piroor** [comment]
Thank you for testing. I've realized that there is one more missed case on the startup process about sidebar contents restored from cache. With the commit 66102b5 odd indentation on the startup should go away.

**Comment by azizLIGHT** [comment]
In preliminary tests, I don't see it anymore on Firefox Nightly 68.0a1 (2019-05-09) (64-bit) and TST dev build 3.0.11.9106. 
I will keep testing to confirm more. Thanks for the fix!

**Comment by azizLIGHT** [comment]
Tested again on Nightly 68.0a1 (2019-05-11) (64-bit) + TST 3.0.11.9109 and I cannot reproduce the issue anymore. I consider it fixed and will close the issue.
