### ISSUE TITLE
Problem with Selecting Tabs with the Shift Key

### ISSUE THREAD

**Issue by aFineBoi** [piroor/treestyletab#3177]
## Steps to reproduce
1. Open Firefox with TST
2. Open tabs in a tree style manner
3. Select multiple tabs by clicking a upper tab, holding down _shift_ key, and clicking a lower tab. You selection should include the clicked upper and lower tabs, and the tabs in between
4. Drag the selected tabs with your mouse to an empty area to open a new window
## Expected result
All selected tabs are move and sorted as what it was
## Actual result
The first tab (the upper tab that you clicked) is omitted

**Comment by piroor** [comment]
Please fill the issue template.

**Comment by piroor** [comment]
The template: https://raw.githubusercontent.com/piroor/treestyletab/trunk/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by aFineBoi** [comment]
> Please fill the issue template.

Done

**Comment by irvinm** [comment]
> > Please fill the issue template.
> 
> Done

You forgot to include:


## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:
