### ISSUE TITLE
Wrong tab selected after closing, reopening and closing again

### ISSUE THREAD

**Issue by personalmountains** [piroor/treestyletab#3559]
Windows 10, Firefox 126.0, TST 4.0.15

With these tabs (`Parent` and `Other` are siblings):

    Parent
     \- Child
    Other

1) Select `Child` by clicking the tab.
2) Close `Child` by clicking the `X`. The `Parent` tab is selected.
3) Reopen the `Child` tab with the menu `History/Recently Closed Tabs/Child`. The `Child` tab is selected.
4) Close `Child` again by clicking the `X`. The `Other` tab is selected instead of `Parent`.

I'm attaching my settings in case I have something weird: [configs-treestyletab@piro.sakura.ne.jp.json](https://github.com/piroor/treestyletab/files/15437144/configs-treestyletab%40piro.sakura.ne.jp.json)

**Comment by piroor** [comment]
Thanks, I couldn't find out the minimum steps to reproduce this problem for a long time. The commit 3cc2a56 should fix this.

**Comment by personalmountains** [comment]
@piroor Note that this problem is not completely fixed. The same thing happens once in a while, but it's intermittent and I don't know how to reproduce it consistently.

**Comment by piroor** [comment]
Yes, I still need more help to clarify conditions to reproduce. Please report again if you successfully find out it.
