### ISSUE TITLE
auto hide

### ISSUE THREAD

**Issue by mighelch** [piroor/treestyletab#801]
ff v34.0 tst v0.15.2014120101
When i move cursor toward the border of window, tab bar won't pop up.

**Comment by ClefAria** [comment]
I have this same issue. Glad to know that I wasn't just hallucinating, because it's a very strange bug. I reverted to 0.14 and it immediately went away. I hope this gets fixed soon!

**Comment by gene-pavlovsky** [comment]
0.14 works fine indeed...

**Comment by emperortomato** [comment]
Experiencing the same issue on 0.15. I have reverted to 0.14. For me, this problem doesn't seem to occur on *all* webpages with 0.15 -- only some. For instance, I would have the issue when viewing VMware documentation or KB articles, or when viewing our internal supaCMDB/easyCMDB site, but other pages would allow the tabs to unhide correctly. I am wondering if the issue has something to do with pages that use frames?

**Comment by ClefAria** [comment]
It's disheartening that this hasn't been addressed or even acknowledged in two months. Not leaving 0.14 until I know it's fixed.

**Comment by piroor** [comment]
Some changes are introduced around calculation of event coordinates by recent commits. Could you try the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by Qiaoj** [comment]
nope, the problem is still here

When you move fast enough to the edge, there is dead zone here. Delay is set to 0 mls.

**Comment by piroor** [comment]
OK, I finally found what is the problem. The commit ff9b670d179635d0983723790d00d5b5f406c58c fixes it. Could you try the development build? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by gene-pavlovsky** [comment]
Hey Piro, nice to see you found time to improve TST. The latest dev build seems to work, auto-show is working properly for me now. Still want to do some more testing and check if the other issue is fixed as well (on the last official build auto-hide sometimes doesn't work).

**Comment by ClefAria** [comment]
The auto-hide issue is gone with the newest nightly, but now I notice sometimes I need to click on a page before the auto-hide begins working at all (until I do, the tab bar won't pop out of the left no matter what)

**Comment by Qiaoj** [comment]
Yep, now is good. Thank you!

**Comment by gene-pavlovsky** [comment]
Latest nightly still doesn't auto-hide occasionally. Wherever I move the
mouse or click - on the page, address bar, tab bar, page again etc. - the
tab bar just stays visible. The only way to hide it in this case is to
switch to some other tab and move the mouse around (but sometimes this
doesn't help either, looks like it might depend on which tab is selected or
something...).

**Comment by piroor** [comment]
For remote/in-process tabs, TST unexpectedly failed to handle mouse events after tabs' remoteness are changed. By recent commits this problem is resolved and "auto hide" works well for me. Could you try the new development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by ClefAria** [comment]
I just installed the nightly from March 13th, and this issue I posted in this thread still exists: https://github.com/piroor/treestyletab/issues/801#issuecomment-77551013

**Comment by walkero-gr** [comment]
On my System with Firefox 41.0, the latest version from 25/9 looks that fixes the problem with the fullscreen. Great job and thank you.

**Comment by ClefAria** [comment]
How do I download "the latest version from 25/9"? I can't find it.

**Comment by piroor** [comment]
I' ve confirmed a problem https://github.com/piroor/treestyletab/issues/801#issuecomment-77551013 and the commit 809cc403c6ca4bc43b24c2d75f72f22146b13bc0 should fix it. Could you confirm it has been actually fixed on [the development build](http://piro.sakura.ne.jp/xul/xpi/nightly/)? Then this issue should be closed.

**Comment by ClefAria** [comment]
Finally! After dealing with this issue for so long, it's finally gone! Thanks so much, you can close this issue now. :)
