### ISSUE TITLE
Child tabs don't get indented

### ISSUE THREAD

**Issue by wbarroz** [piroor/treestyletab#807]
Using Firefox 34 and Vimperator 3.8.3.
Firefox get updated couple of times recently, and after that I notice the child tabs don't get indented, the configuration didn't change, I checked that "new tabs" for middle-click is set as child, but the behaviour is to create as a independent tab, always.

**Comment by jimbo1qaz** [comment]
This is a real bug. I have experienced it many times in the past, seemingly randomly. It came back just now!...

**Comment by piroor** [comment]
Is this an appearance issue or a tree structure issue? If tabs opened from links are not attached to the current tab for you, then the problem does't happen for me and it seems to be fixed at the latest development build, http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by GollyJer** [comment]
It was a structure thing.  Tabs meant to be children were opening as completely new branches.  Just installed the latest nightly (2015-03-06) and things are working great again with Firefox 37.

**Comment by piroor** [comment]
Can I close this issue?

**Comment by jimbo1qaz** [comment]
Why does it seem like every few months, the issue reappears, and can only be fixed by nightly? Does this addon hook some very unstable part of Firefox internal API?

**Comment by auralarch** [comment]
This is still an issue for me (and has been for several months).  It is a tree structure issue, not an appearance issue.  And it does not happen always.  For instance, if I manually move the most recently created tab to become a child, then anymore new tabs created by middle-click will be children (only from that same parent).  I also discovered that tabs are created as expected when manually selecting it in the context menu instead of middle-click.  But that kills the convenience & value of the middle click option.
Some sites seem to work better for me than others- eBay seems to always create children properly.  Amazon & Google, however, never do.  Haven't noticed any other site-based patterns, although it does seem to work correctly more often if I only have a few tabs open in one window- more tabs & multiple windows seems to make no tabs become children.  (I have i7 @ 3Ghz w/20GB of RAM so memory & CPU aren't really an issue.)
I'm on the ESR channel, running OS X 10.8.5 most of the time.  I'm also using TMP which I know can conflict with TST although this has not been an issue for me before.
I have not yet tested the nightly.

**Comment by jimbo1qaz** [comment]
Test the nightly addon build, not Firefox nightly.

**Comment by auralarch** [comment]
I have been testing the latest nightly build of the addon for several weeks.  Most of the issues have been corrected.  Thank you very much!
The single, most notable & important exception that remains for me is when I middle-click on results of a Google search: they still open as sibling tabs (or independent if no parent). As mentioned before, if I manage to remember to manual make the 1st clicked link a child tab, the subsequent middle-clicked links will also be created as child tabs.
I couldn't help but wonder if this behavior was somehow the unintentional result of some other setting or conflict with another addon. So I created a new profile into which I only loaded the same nightly build and the problem persisted for me- although I still wonder if some global setting, or even my platform or other unknown factor could be interfering & in some way causing this issue.  Because it doesn't seem like anyone else is affected by this issue.  Perhaps there are others who remain silent?
As I can not provide any useful information I do not expect any action- I just wanted to report my experiences should they prove relevant at some point.
Thank you!

**Comment by roysc** [comment]
When I first had this issue, I noticed it disappeared when I used the "Flat" theme, so I used that for several months. Then it returned (in non-nightly), no matter what theme I used, with the latest Firefox update. However, I installed the nightly and it's working well again for all themes; I haven't had @auralarch's behavior either.

**Comment by takuma-saito** [comment]
When I update my Firefox and addons, same issue occured for me. But, After I read the above comments and install of nightly build (http://piro.sakura.ne.jp/xul/xpi/nightly/), the problem was fixed.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by jimbo1qaz** [comment]
I didn't notice this bug recently.

From past observations, the bugs tends to show up on only some computers.
Only waiting or resetting fixes things. Alternatively, the bug could be
Firefox-version-specific, and I'm just misremembering that resetting helps.
