### ISSUE TITLE
Tabs disappear and are not reaccessible after customizing menu and toolbar

### ISSUE THREAD

**Issue by CybrCat** [piroor/treestyletab#899]
#### Steps to reproduce:
1. Open "Customize" from overflow menu (making toolbar changes is not necessary to reproduce)
2. "Exit Customize" 
3. Open "Customize" a second time
4. "Exit Customize"
#### Behavior:

When entering toolbar customize mode tree style tabs is hidden and replaced with the default tabs on top. When exiting customize mode the second time, tree style tabs are not restored again. There appears to be no way to restore them again.

Windows 8.1
Firefox 38.0.5

**Comment by overlord624** [comment]
I've seen this happen as well, the bug persists even after restarting the browser.

There is a very simple work-around, you can go into the addon's options screen and change the tab bar location and optionally set it back to it's initial location.

**Comment by PhillipKC** [comment]
Thanks overlord, that fixes it. The issue is still reproducible by going back into customize twice again, but at least that is a fix. I noticed the issue is also consistently reproducible on Firefox Portable 38.0.5 for what it's worth.

**Comment by piroor** [comment]
I've found a mistake around toolbar customization and the commit daa27ee336566ab326638eeb01a65498514d29e7 fixes it. Does this issue solved by the commit?
(You can try the development build with the fix from http://piro.sakura.ne.jp/xul/xpi/nightly/ )

**Comment by overlord624** [comment]
I can confirm that the bug persists in the 13Jun nightly. Entering and leaving customize corrupts the UI as with the initial ticket.

**Comment by minus7** [comment]
Fix seems to work for me. Before the tree lost the scrollbar when exiting customize or reverted to default tabs (not entirely sure when which happened). The Firefox main menu popup is displaced after entering customize mode now however: it appears almost on the bottom of the screen.

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by overlord624** [comment]
With the latest nightly (0.16.2015110900a231602), the addon causes the menu bar to always dislocated (ie rendered over title bar instead of under it) as soon as FF starts. The tab sidebar works just fine and restores itself properly when exiting customize.

**Comment by piroor** [comment]
> the addon causes the menu bar to always dislocated

Sorry, it was a regression and already fixed on the latest development build.

**Comment by minus7** [comment]
Just updated to the latest nightly (14-Dec-2015 23:26) and the menu is still displaced after using customize mode.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
